### ISSUE TITLE
`sx` script replacement for `startx` doesn't exist anymore ?

### ISSUE THREAD

**Issue by Atralb** [pid1/dotfiles#1]
Hi there, sorry to bother you with an issue for this, but you shared one of your scripts [here](https://www.reddit.com/r/archlinux/comments/5a51mx/whats_the_difference_between_xinit_and_startx/d9dr8df?utm_source=share&utm_medium=web2x&context=3) the past and it doesn't seem to be available in your repo anymore. Do you still have it perhaps ?

Thanks in advance.

**Comment by pid1** [comment]
A similar but much better version of what that wrapper script was exists [here](https://github.com/Earnestly/sx). I'd recommend making use of that.
